# Generated by Django 5.0 on 2023-12-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
