# Generated by Django 5.0.1 on 2024-01-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
